import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  UIProvider,
  ArrayProvider,
} from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crypto Scan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UIProvider>
          <ArrayProvider>
            {children}
          </ArrayProvider>
        </UIProvider>
      </body>
    </html>
  );
}
